# Generated by Django 4.0.3 on 2022-04-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_description_products_display_products_gpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='remise',
        ),
    ]
